#!/bin/bash
src="$(realpath "${BASH_SOURCE[0]}")"
SCRIPT_DIR=$( cd -- "$( dirname -- "$src" )" &> /dev/null && pwd )
real_script_dir="$(realpath "$SCRIPT_DIR")"
python3.10 "$real_script_dir/run.py" $@
